export interface NursingAssessment {
  // 1. Dati Generali
  academicYear: string;
  courseYear: string;
  studentName: string;
  studentId: string;
  internshipPeriod: string;
  internshipLocation: string;
  ward: string;
  clinicalGuide: string;
  coordinator: string;
  tutor: string;
  
  // Patient Info
  patientGender: string;
  patientAge: string;
  nationality: string;
  language: string;
  maritalStatus: string;
  referencePerson: string;
  admissionDate: string;
  admissionType: string;
  admissionTransferFrom: string;
  origin: string;
  arrivalMode: string;
  medicalDiagnosis: string;
  admissionReason: string;
  pastMedicalHistory: Array<{ date: string; pathology: string }>;
  dataSource: string;
  dataSourceOther: string;
  
  // MODEL 1
  generalHealth: string;
  healthPromotion: string;
  preventiveActions: string;
  alcoholConsumption: boolean;
  alcoholDetails: string;
  smoking: boolean;
  smokingDetails: string;
  allergies: boolean;
  allergyDetails: string;
  physicalAppearance: string;
  homeTherapy: Array<{ drug: string; reason: string; dose: string; schedule: string; route: string }>;
  model1Notes: string;
  model1Status: string;
  conleyScore: number;
  fallRisk: boolean;

  // MODEL 2
  eatingHabits: string;
  dietaryRestrictions: string;
  foodAllergies: string;
  weightChange: string;
  weightChangeAmount: string;
  appetite: string;
  appetiteAlterations: string[];
  currentWeight: string;
  weightNotDetectedReason: string;
  height: string;
  temperature: string;
  temperatureLocation: string;
  idealWeight: string;
  bmi: string;
  weightClass: string;
  obesityGrade: string;
  basalMetabolism: string;
  caloricNeed: string;
  dentition: string;
  dentitionProsthesisType: string;
  swallowing: string;
  swallowingAlteration: string;
  enteralNutrition: string;
  enteralNutritionType: string;
  enteralNutritionSize: string;
  enteralNutritionDate: string;
  parenteralNutrition: string;
  capillaryGlycemia: string;
  
  malnutritionTool: string;
  malnutritionRiskScore: string;
  malnutritionRisk: boolean;

  skinTemperature: string;
  skinColdLocation: string;
  skinWarmLocation: string;
  skinColor: string;
  skinColorOther: string;
  skinTurgor: string;
  skinMoisture: string;
  itching: boolean;
  itchingLocation: string;
  erythema: boolean;
  erythemaLocation: string;
  edema: boolean;
  edemaLocation: string;
  edemaGrade: string;
  tc: string;

  vascularAccess: boolean;
  vascularAccessType: string;
  vascularAccessDetailsType: string;
  vascularAccessLocation: string;
  vascularAccessDate: string;
  vascularAccessDressing: string;
  vascularAccessDressingDate: string;
  exitSiteScale: string;
  exitSiteScore: string;

  skinIntegrity: boolean;
  surgicalWounds: string;
  skinLesions: string;
  otherSkinLesions: string;
  skinAppendagesAlterations: string;

  bradenScore: number;
  pressureUlcerRisk: string;
  pressureUlcerRiskFactors: string;
  pressureUlcerRiskFactorsDetails: string;

  throatScaleScore: string;
  model2Notes: string;
  model2Status: string;

  // MODEL 3
  urinationType: string;
  urinationFrequency: string;
  urinaryIncontinenceTypes: string[];
  urinaryRetention: string;
  urinaryRetentionResidue: string;
  otherUrinaryAlterations: string[];
  pollakiuriaFrequency: string;
  urineCharacteristics: string;
  urineAlterationsDescription: string;
  diuresis24h: string;
  diuresisAlteration: string;
  incontinenceAids: string;
  incontinenceAidsDetails: string;
  urinaryCatheter: string;
  urinaryCatheterDate: string;
  urinaryCatheterDetails: string;
  urinaryCatheterManagement: string;
  urinaryCatheterManagedBy: string;
  urinaryStoma: string;
  urinaryStomaDetails: string;
  urinaryStomaManagement: string;
  urinaryStomaManagedBy: string;
  
  bowelFrequency: string;
  lastBowelMovement: string;
  bowelAlterations: string;
  bowelAlterationsTypes: string[];
  bowelIncontinenceType: string;
  bowelIncontinenceAids: string;
  bowelIncontinenceAidsDetails: string;
  laxatives: string;
  laxativesDetails: string;
  stoolCharacteristics: string;
  stoolAlterationsDetails: string;
  bristolScale: string;
  romaIIIScale: string;
  abdomenExam: string;
  peristalsis: string;
  peristalsisType: string;
  bowelStoma: string;
  bowelStomaDetails: string;
  bowelStomaManagement: string;
  bowelStomaManagedBy: string;
  drains: string;
  drainsDetails: string;
  eliminationOtherObservations: string;
  model3Notes: string;
  model3Status: string;

  // MODEL 4
  energyLevel: string;
  leisureActivities: string;
  exerciseRoutine: string;
  funcAlimentazione: string;
  funcCuraAspetto: string;
  funcBagno: string;
  funcMobilitaGen: string;
  funcGabinetto: string;
  funcCucinare: string;
  funcMobilitaLetto: string;
  funcCasa: string;
  funcVestirsi: string;
  funcSpesa: string;

  assumedPosition: string;
  decubitusType: string;
  muscleTone: string;
  muscleToneAlterations: string;
  muscleStrength: string;
  muscleStrengthAlterations: string;
  jointExcursion: string;
  jointExcursionAlterations: string;
  balance: string;
  walking: string;
  walkingAlterations: string;
  prosthesis: string;
  prosthesisDetails: string;
  barthelScore: string;
  generalAppearance: string;

  respiratoryFunction: string;
  respiratoryRate: string;
  spo2: string;
  breathingDepth: string;
  breathingQuality: string;
  dyspneaType: string;
  breathingAlterations: string[];
  breathingPathological: string;
  breathingOtherAlterations: string;
  respiratoryNoises: string;
  respiratoryNoisesDetails: string;
  coughReflex: string;
  cough: string;
  coughDetails: string;
  sputum: string;
  sputumDetails: string;
  sputumAbility: string;
  respiratoryDevice: string;
  respiratorySupport: string;

  pulseRate: string;
  pulseLocation: string;
  pulseType: string;
  pulseRhythm: string;
  pulseAmplitude: string;
  bloodPressureValue: string;
  bloodPressureLocation: string;
  bloodPressurePosture: string[];
  capillaryRefill: string;

  model4Notes: string;
  model4Status: string;

  // Sleep
  sleepHours: string;
  sleepRested: boolean;
  sleepMeds: string;
  consciousness: string;
  orientation: string;
  pain: boolean;
  painNrs: string;
  selfDescription: string;
  maritalRole: string;
  stressFactors: string;
  religiousRestrictions: string;

  // Care Plan
  carePlans: Array<{ problem: string; objective: string; plannedInterventions: string; implementedInterventions: string; evaluation: string }>;
}

export const defaultValues: NursingAssessment = {
  academicYear: '',
  courseYear: '',
  studentName: '',
  studentId: '',
  internshipPeriod: '',
  internshipLocation: '',
  ward: '',
  clinicalGuide: '',
  coordinator: '',
  tutor: '',
  patientGender: '',
  patientAge: '',
  nationality: '',
  language: '',
  maritalStatus: '',
  referencePerson: '',
  admissionDate: '',
  admissionType: '',
  admissionTransferFrom: '',
  origin: '',
  arrivalMode: '',
  medicalDiagnosis: '',
  admissionReason: '',
  pastMedicalHistory: [],
  dataSource: '',
  dataSourceOther: '',
  
  generalHealth: '',
  healthPromotion: '',
  preventiveActions: '',
  alcoholConsumption: false,
  alcoholDetails: '',
  smoking: false,
  smokingDetails: '',
  allergies: false,
  allergyDetails: '',
  physicalAppearance: '',
  homeTherapy: [],
  model1Notes: '',
  model1Status: '',
  conleyScore: 0,
  fallRisk: false,
  
  eatingHabits: '',
  dietaryRestrictions: '',
  foodAllergies: '',
  weightChange: '',
  weightChangeAmount: '',
  appetite: '',
  appetiteAlterations: [],
  currentWeight: '',
  weightNotDetectedReason: '',
  height: '',
  temperature: '',
  temperatureLocation: '',
  idealWeight: '',
  bmi: '',
  weightClass: '',
  obesityGrade: '',
  basalMetabolism: '',
  caloricNeed: '',
  dentition: '',
  dentitionProsthesisType: '',
  swallowing: '',
  swallowingAlteration: '',
  enteralNutrition: '',
  enteralNutritionType: '',
  enteralNutritionSize: '',
  enteralNutritionDate: '',
  parenteralNutrition: '',
  capillaryGlycemia: '',
  malnutritionTool: '',
  malnutritionRiskScore: '',
  malnutritionRisk: false,
  skinTemperature: '',
  skinColdLocation: '',
  skinWarmLocation: '',
  skinColor: '',
  skinColorOther: '',
  skinTurgor: '',
  skinMoisture: '',
  itching: false,
  itchingLocation: '',
  erythema: false,
  erythemaLocation: '',
  edema: false,
  edemaLocation: '',
  edemaGrade: '',
  tc: '',
  vascularAccess: false,
  vascularAccessType: '',
  vascularAccessDetailsType: '',
  vascularAccessLocation: '',
  vascularAccessDate: '',
  vascularAccessDressing: '',
  vascularAccessDressingDate: '',
  exitSiteScale: '',
  exitSiteScore: '',
  skinIntegrity: true,
  surgicalWounds: '',
  skinLesions: '',
  otherSkinLesions: '',
  skinAppendagesAlterations: '',
  bradenScore: 0,
  pressureUlcerRisk: '',
  pressureUlcerRiskFactors: '',
  pressureUlcerRiskFactorsDetails: '',
  throatScaleScore: '',
  model2Notes: '',
  model2Status: '',

  urinationType: '',
  urinationFrequency: '',
  urinaryIncontinenceTypes: [],
  urinaryRetention: '',
  urinaryRetentionResidue: '',
  otherUrinaryAlterations: [],
  pollakiuriaFrequency: '',
  urineCharacteristics: '',
  urineAlterationsDescription: '',
  diuresis24h: '',
  diuresisAlteration: '',
  incontinenceAids: 'false',
  incontinenceAidsDetails: '',
  urinaryCatheter: 'No',
  urinaryCatheterDate: '',
  urinaryCatheterDetails: '',
  urinaryCatheterManagement: 'Si',
  urinaryCatheterManagedBy: '',
  urinaryStoma: 'false',
  urinaryStomaDetails: '',
  urinaryStomaManagement: 'Si',
  urinaryStomaManagedBy: '',
  
  bowelFrequency: '',
  lastBowelMovement: '',
  bowelAlterations: 'false',
  bowelAlterationsTypes: [],
  bowelIncontinenceType: '',
  bowelIncontinenceAids: 'false',
  bowelIncontinenceAidsDetails: '',
  laxatives: 'false',
  laxativesDetails: '',
  stoolCharacteristics: '',
  stoolAlterationsDetails: '',
  bristolScale: '',
  romaIIIScale: '',
  abdomenExam: '',
  peristalsis: '',
  peristalsisType: '',
  bowelStoma: 'false',
  bowelStomaDetails: '',
  bowelStomaManagement: 'Si',
  bowelStomaManagedBy: '',
  drains: 'false',
  drainsDetails: '',
  eliminationOtherObservations: '',
  model3Notes: '',
  model3Status: '',

  energyLevel: '',
  leisureActivities: '',
  exerciseRoutine: '',
  funcAlimentazione: '',
  funcCuraAspetto: '',
  funcBagno: '',
  funcMobilitaGen: '',
  funcGabinetto: '',
  funcCucinare: '',
  funcMobilitaLetto: '',
  funcCasa: '',
  funcVestirsi: '',
  funcSpesa: '',

  assumedPosition: '',
  decubitusType: '',
  muscleTone: '',
  muscleToneAlterations: '',
  muscleStrength: '',
  muscleStrengthAlterations: '',
  jointExcursion: '',
  jointExcursionAlterations: '',
  balance: '',
  walking: '',
  walkingAlterations: '',
  prosthesis: 'false',
  prosthesisDetails: '',
  barthelScore: '',
  generalAppearance: '',

  respiratoryFunction: '',
  respiratoryRate: '',
  spo2: '',
  breathingDepth: '',
  breathingQuality: '',
  dyspneaType: '',
  breathingAlterations: [],
  breathingPathological: '',
  breathingOtherAlterations: '',
  respiratoryNoises: '',
  respiratoryNoisesDetails: '',
  coughReflex: '',
  cough: '',
  coughDetails: '',
  sputum: '',
  sputumDetails: '',
  sputumAbility: '',
  respiratoryDevice: '',
  respiratorySupport: '',

  pulseRate: '',
  pulseLocation: '',
  pulseType: '',
  pulseRhythm: '',
  pulseAmplitude: '',
  bloodPressureValue: '',
  bloodPressureLocation: '',
  bloodPressurePosture: [],
  capillaryRefill: '',

  model4Notes: '',
  model4Status: '',

  sleepHours: '',
  sleepRested: true,
  sleepMeds: '',
  consciousness: '',
  orientation: '',
  pain: false,
  painNrs: '',
  selfDescription: '',
  maritalRole: '',
  stressFactors: '',
  religiousRestrictions: '',
  carePlans: []
};
